
<pre>
Mod_python error: "PythonHandler index"

Traceback (most recent call last):

  File &quot;/usr/lib/python3/dist-packages/mod_python/apache.py&quot;, line 402, in HandlerDispatch
    result = obj(req)

  File &quot;/home/gizmore/PycharmProjects/pygdo/index.py&quot;, line 26, in handler
    loader.load_modules_db()

  File &quot;/home/gizmore/PycharmProjects/pygdo/gdo/base/ModuleLoader.py&quot;, line 84, in load_modules_db
    fs = self.gdo_import(db.gdo_val(&#x27;module_name&#x27;))

  File &quot;/home/gizmore/PycharmProjects/pygdo/gdo/base/ModuleLoader.py&quot;, line 30, in gdo_import
    mn = importlib.import_module(&quot;gdo.&quot; + name)

  File &quot;/usr/lib/python3.10/importlib/__init__.py&quot;, line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1050, in _gcd_import

  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1027, in _find_and_load

  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 1006, in _find_and_load_unlocked

  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 688, in _load_unlocked

  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 883, in exec_module

  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 241, in _call_with_frames_removed

  File &quot;/home/gizmore/PycharmProjects/pygdo/gdo/login/__init__.py&quot;, line 1, in &lt;module&gt;
    from gdo.login.module_login import module_login

  File &quot;/home/gizmore/PycharmProjects/pygdo/gdo/login/module_login.py&quot;, line 4, in &lt;module&gt;
    from gdo.core.GDT_Password import Password, GDT_Password

  File &quot;/home/gizmore/PycharmProjects/pygdo/gdo/core/GDT_Password.py&quot;, line 1, in &lt;module&gt;
    import bcrypt

ModuleNotFoundError: No module named &#x27;bcrypt&#x27;

</pre>
